name: IntelliJ plugin verifier
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11.x.x
    - name: Build the plugin using Gradle
      run: ./gradlew buildPlugin
    
    - name: IntelliJ Plugin Verifier
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.6
      with:
        ide-versions: |
          ideaIC:2019.3.5
          ideaIU:2019.3.5
          ideaIC:2020.1.1
          ideaIU:2020.1.1
          ideaIC:LATEST-EAP-SNAPSHOT
          ideaIU:LATEST-EAP-SNAPSHOT
